[build]
builder = "NIXPACKS"
nixpacksVersion = "1.35.0"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
